#!/bin/zsh
# step1  数据的整合
file1=ThermoGlobe_21_05_20
file2=Davies2013-sup-0008-data_table5_eq_area_data_only_detailed.dat
file3=WHFDC
file4=0Pasquale_et_al_2014_RSER
file5=Geothopica
file6=5*.zwt

awk '{if($1!="#"){print $2,$1,$3}}' $file1 > 1.tmp
#awk '{if($1!="#"){print $1,$2,$7}}' $file2 > 2.tmp
#awk '{if($1!="#"){print $2,$1,$3}}' $file3 > 3.tmp
awk '{if($1!="#"){print $1,$2,$3}}' $file5 > 5.tmp
cat *.tmp > ALL.zwt

rm *.tmp
# step1  数据的整合End
